### ISSUE TITLE
Host App on Modulus returns error from Simple Schema

### ISSUE THREAD

**Issue by TimoRuetten** [aldeed/meteor-simple-schema#154]
Hey,

after updating my project localy and add an Update (added Autoform and Simple Schema) everything works fine localy. After deploing this project to modulus this Error appears:

``` javascript
throw(ex);
^
Error: Can't find npm module 'string'. Did you forget to call 'Npm.depends' in package.js within the 'aldeed:simple-schema' package?
    at Object.Npm.require (/mnt/data/2/programs/server/boot.js:106:17)
    at invalidKeys (packages/aldeed:simple-schema/simple-schema.js:2)
    at /mnt/data/2/programs/server/packages/aldeed:simple-schema.js:1921:4
    at /mnt/data/2/programs/server/packages/aldeed:simple-schema.js:2858:3
    at /mnt/data/2/programs/server/boot.js:161:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/data/2/node_modules/underscore/underscore.js:79:11)
    at /mnt/data/2/programs/server/boot.js:82:5
[2014-09-15T09:05:49.475Z] Application CRASH detected. Exit code 8.
[2014-09-15T09:05:50.181Z] Application restarted.

/mnt/data/2/node_modules/fibers/future.js:173
```

My Application is crashed now and its not possible to start my server correctly with Simple Schema. Any idea how to fix it by myself or maybe an update by you ?

**Comment by sibanand-cis** [comment]
did they fix this issue?

**Comment by Visudare** [comment]
Yes. I currently have no problems with modulus anymore. So I think they've fixed it.

**Comment by sibanand-cis** [comment]
I'm getting the same issue, did you get any  solution. 
at Object.Npm.require (/opt/project/app/programs/server/boot.js:117:17)[0.0.0.0] 
[0.0.0.0]     at expectedType (packages/aldeed:simple-schema/simple-schema.js:8:1)[0.0.0.0] 
[0.0.0.0]     at /opt/project/app/programs/server/packages/aldeed_simple-schema.js:2015:4[0.0.0.0] 
[0.0.0.0]     at /opt/project/app/programs/server/packages/aldeed_simple-schema.js:2983:3[0.0.0.0] 
[0.0.0.0]     at /opt/project/app/programs/server/boot.js:175:10[0.0.0.0] 
[0.0.0.0]     at Array.forEach (native)[0.0.0.0] 
[0.0.0.0]     at Function._.each._.forEach (/opt/project/app/programs/server/node_modules/underscore/underscore.js:79:11)[0.0.0.0] 
[0.0.0.0]     at /opt/project/app/programs/server/boot.js:86:5[0.0.0.0] 
[0.0.0.0] error: Forever detected script exited with code: 8[0.0.0.0] 
[0.0.0.0] error: Script restart attempt #27[0.0.0.0]

**Comment by Visudare** [comment]
Hm. The best would be to contact modulus - I did the same. The error then disappeared. It would be also good when you update your modulus on your machine because modulus creates the node project of your meteor - and maybe there is also an error.

**Comment by sibanand-cis** [comment]
But I'm using codeship to deploy. is that matter to install modulus on local?, Although I have installed and tried to deploy from the local not get success. getting error 
    
    Meteor Up: Production Quality Meteor Deployments
    ------------------------------------------------

    Building Started: /home/rof/clone

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: spawn ENOENT
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by Visudare** [comment]
Aouh ... Than I cant give you a hint. In my case the problem was my modulus installation and modulus itself fixed smth to get it run.

**Comment by aldeed** [comment]
@sibanand-cis check with the mup folks. Seems like an issue there.
