### ISSUE TITLE
Error: Can't find npm module 'string'. Did you forget to call 'Npm.depends' in package.js within the 'aldeed_simple-schema' package?

### ISSUE THREAD

**Issue by sibanand-cis** [aldeed/meteor-simple-schema#353]
Hi Team,

While deploying on production we are getting following error, Please help me if possible.

    Error: Can't find npm module 'string'. Did you forget to call 'Npm.depends' in package.js within the 'aldeed_simple-schema' package?

    at Object.Npm.require (/opt/project/app/programs/server/boot.js:117:17)[0.0.0.0] 
    [0.0.0.0]     at expectedType (packages/aldeed:simple-schema/simple-schema.js:8:1)[0.0.0.0] 
    [0.0.0.0]     at /opt/project/app/programs/server/packages/aldeed_simple-schema.js:2015:4[0.0.0.0] 
    [0.0.0.0]     at /opt/project/app/programs/server/packages/aldeed_simple-schema.js:2983:3[0.0.0.0] 
    [0.0.0.0]     at /opt/project/app/programs/server/boot.js:175:10[0.0.0.0] 
    [0.0.0.0]     at Array.forEach (native)[0.0.0.0] 
    [0.0.0.0]     at Function._.each._.forEach         (/opt/project/app/programs/server/node_modules/underscore/underscore.js:79:11)[0.0.0.0] 
    [0.0.0.0]     at /opt/project/app/programs/server/boot.js:86:5[0.0.0.0] 
    [0.0.0.0] error: Forever detected script exited with code: 8[0.0.0.0] 
    [0.0.0.0] error: Script restart attempt #27[0.0.0.0]

**Comment by ddresch** [comment]
Same here @sibanand-cis you found a solution in the meantime?

**Comment by Innarticles** [comment]
Exactly the same error.

**Comment by ssteinerx** [comment]
I have tried updating the string module reference to 3.2.0, moving it into packages.json (as per new convention with meteorhacks:npm, installing string globally via npm, and installing string into my app.

Now it's changed to this: 

Your app is crashing. Here's the latest log.


/Users/ssteiner/.meteor/packages/velocity_meteor-tool/.1.1.3_4.1nvsfdi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Cannot find module 'string'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/private/var/folders/bw/w312ywz17pv4k41b9wk2l9z00000gn/T/meteor-test-run130ldko/.meteor/local/build/programs/server/boot.js:130:18)
    at expectedType (packages/aldeed:simple-schema/simple-schema.js:8:1)
    at /private/var/folders/bw/w312ywz17pv4k41b9wk2l9z00000gn/T/meteor-test-run130ldko/.meteor/local/build/programs/server/packages/aldeed_simple-schema.js:2022:4
    at /private/var/folders/bw/w312ywz17pv4k41b9wk2l9z00000gn/T/meteor-test-run130ldko/.meteor/local/build/programs/server/packages/aldeed_simple-schema.js:2990:3
    at /private/var/folders/bw/w312ywz17pv4k41b9wk2l9z00000gn/T/meteor-test-run130ldko/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by ssteinerx** [comment]
I have come up with an icky but working solution.  For some reason, string.js is included in the simple-schema package.

I replaced it with the current version, and patched line 8 of simple-schema.js to read:

```
  S = Npm.require("./string");
```
And it gets past the dependency, my cucumber tests work, and everything appears hunky-dunky as they say.

Whether something else will go wrong later on, I don't know, but I suspect that the behaviour of NPM.require changed to make it so that the local file wasn't being pulled in and so an explicit path was necessary.

A stupid solution to a backwards incompatibility problem, presumably in Npm.require that should have been picked up by somebody's tests long before this.

I'll leave it for smarter people to figure out where that should be...

**Comment by ssteinerx** [comment]
I have a branch that solves this issue for me.  

https://github.com/ssteinerx/meteor-simple-schema/tree/string-fix

Check the string-fix branch out into your packages directory of your app, remove aldeed:simple-schema, then add it again and it will pull the local copy in.

Please let me know whether this solves your issues and, if so, I'll submit a pull request.

Thanks,

ssteinerX

**Comment by aldeed** [comment]
stringjs dependency will be removed in upcoming release
