### ISSUE TITLE
problems creating global Schema object

### ISSUE THREAD

**Issue by lyricalpolymath** [aldeed/meteor-simple-schema#471]
Hello, first of all thanks for the great packages.

I'm having a hard time creating a global Schema object 

if I create in 
`/common/models/SomeCollection.js`
the following code 

```
if (Schemas == undefined) {
    //global schemas is undefined > create it
    Schemas = {};
}

//a schema that will end in global but not to 

//register the schema in the global object
Schemas.SomeSchema = new SimpleSchema({ ... });

//assign the schema
SomeCollection.attachSchema(Schemas.SomeSchema);
```

I always get this `ReferenceError: Schemas is not defined`
```
W20151012-19:11:16.092(2)? (STDERR) 
W20151012-19:11:16.092(2)? (STDERR) /Users/b/.meteor/packages/meteor-tool/.1.1.4.1d1i42q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151012-19:11:16.092(2)? (STDERR)                                             throw(ex);
W20151012-19:11:16.092(2)? (STDERR)                                                   ^
W20151012-19:11:16.092(2)? (STDERR) ReferenceError: Schemas is not defined
W20151012-19:11:16.092(2)? (STDERR)     at app/common/SomeCollection.js:3:44
W20151012-19:11:16.093(2)? (STDERR)     at app/common/SomeCollection.js:7:3
W20151012-19:11:16.093(2)? (STDERR)     at /Users/xxxxx/Documents/projectDir/.meteor/local/build/programs/server/boot.js:222:10
W20151012-19:11:16.093(2)? (STDERR)     at Array.forEach (native)
W20151012-19:11:16.093(2)? (STDERR)     at Function._.each._.forEach (/Users/xxxxx/.meteor/packages/meteor-tool/.1.1.4.1d1i42q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151012-19:11:16.093(2)? (STDERR)     at /Users/xxxxx/Documents/projectDir/.meteor/local/build/programs/server/boot.js:117:5
```

I keep getting the ReferenceError even after trying all these solutions:
- checking if it is undefined and create it only afte that
- checking the precedence of execution of the files
- creating the global object in a Meteor.startup, but that gets executed after
- changing the 'Schemas' variable name to something that might not be reserved for some reason
- creating the Schemas as a new Object
- adding Schemas.prototype.SomeSchema instead of Schemas.SomeSchema

none work...
I really don't understand why... also because all other variables like SomeCollection, and even other new SimpleSchemas like the baseschema in [this similar issue](https://github.com/aldeed/meteor-simple-schema/issues/79) do end up in the global scope.

any ideas?

**Comment by lyricalpolymath** [comment]
I found a solution,
I still don't understand why this was happening only with the Schemas object,
but at least it doesn't print out annoying warnings.

To solve the issue put the following lines in the first file that needs the global Schemas

```
if(typeof Schemas === "undefined") {
    Schemas = function Schemas() {}
}
```

after this Schemas will be globally accessible by all other subsequently loaded files.

It is safe to add those lines to the beginning of all files who use the Schemas object, in case you decide to rename it and the order changes.
