### ISSUE TITLE
Error thrown during meteor accounts server reset token expiration

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-simple-schema#652]
As suggested by MDG over at https://github.com/meteor/meteor/issues/7734#issuecomment-243326376 this may be a SS bug:

> This seems like a bug in SS dealing with `$push: { "field": { or: ... } }`

```
Exception in setInterval callback: Error: services.password.reset.$or is not allowed by the schema
     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:451:1)
     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:433:1)
     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:185:1)
     at AccountsServer.Ap._expirePasswordResetTokens (packages/accounts-base/accounts_server.js:1137:14)
     at packages/accounts-base/accounts_server.js:1174:14
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at packages/meteor/timers.js:6:1
     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```

**Comment by clayne11** [comment]
You're going to need to post your schema as well.

**Comment by serkandurusoy** [comment]
Hm, that's right. This was in my mind an extension to an already existing issue https://github.com/aldeed/meteor-collection2/issues/344 so I kind of neglected doing that. Here it is:

```js
Meteor.users.attachSchema(new SimpleSchema({
  createdAt: {
    type: Date,
  },
  'services.resume.loginTokens.$.when': {
    type: Date,
    optional: true,
  },
  'services.resume.loginTokens.$.hashedToken': {
    type: String,
    optional: true,
  },
  'services.password.bcrypt': {
    type: String,
  },
  'services.password.srp': {
    type: Object,
    blackbox: true,
    optional: true,
  },
  'services.password.reset.token': {
    type: String,
    optional: true,
  },
  'services.password.reset.email': {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    optional: true,
  },
  'services.password.reset.when': {
    type: Date,
    optional: true,
  },
  'emails.$.address': {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
  },
  'emails.$.verified': {
    type: Boolean,
  },
  'services.email.verificationTokens.$.token': {
    type: String,
    optional: true,
  },
  'services.email.verificationTokens.$.address': {
    type: String,
    regEx: SimpleSchema.RegEx.Email,
    optional: true,
  },
  'services.email.verificationTokens.$.when': {
    type: Date,
    optional: true,
  },
}));
```

**Comment by abernix** [comment]
This can be closed.  This is a Meteor bug; see more in meteor/meteor#7734.

**Comment by abernix** [comment]
I'll clarify that.

It's not a Meteor bug, per se, but the `$unset` update parameter that is being used in Meteor right now ([seen here](https://github.com/meteor/meteor/blob/e86ef3cb47fb4f44a06b35433d94cae4602e7bcc/packages/accounts-base/accounts_server.js#L1143-L1150)) does not match Mongo specification.  While arguably, SimpleSchema shouldn't complain about the _actual_ value which is inside an `$unset` field (as [the Mongo docs indicate here](https://docs.mongodb.com/manual/reference/operator/update/unset/#up._S_unset)), this error helped to identify a confusing `$unset` clause in Meteor.
