### ISSUE TITLE
Server error if I attach schema to user with meteor 1.4.2

### ISSUE THREAD

**Issue by perusopersonale** [aldeed/meteor-simple-schema#671]
I've attached the proposed schema to Meteor.users, but I see this error in console:
```
 Exception in setInterval callback: Error: After filtering out keys not in the schema, your modifier is now empty
at [object Object].doValidate (packages/aldeed_collection2-core.js:416:11)
at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:214:25)
 at AccountsServer.Ap._expireTokens (packages/accounts-base/accounts_server.js:1115:14) 
```
I've checked packages/accounts-base/accounts_server.js history and they change the body of an update using the $pull operator.

**Comment by perusopersonale** [comment]
I was attaching null schema my bad.
