### ISSUE TITLE
new SimpleSchema({ }).validator() returns Undefined

### ISSUE THREAD

**Issue by hich-em** [aldeed/meteor-simple-schema#674]
Hello,

this is my code 
```
import { Meteor } from 'meteor/meteor';
import { SimpleSchema } from 'meteor/aldeed:simple-schema';
import { ValidatedMethod } from 'meteor/mdg:validated-method';
import { rateLimit } from '../../modules/rate-limit.js';
import { Accounts } from 'meteor/accounts-base';

export const createschoolManager = new ValidatedMethod({
  name: 'users.create.schoolManager',
  validate: new SimpleSchema({
    email: { type: String },
    password: { type: String },
    'update.profile.name': { type: String },
    'update.profile.address': { type: String},
    'update.profile.country': { type: String},
    'update.profile.city': { type: String},
    'update.profile.postal_code': { type: String}
  }).validator(),
  run(newUser) {
    const existUser = Accounts.findUserByEmail(newUser.email)
    if (existUser) {
      return {
        "error": "User already uses this email to register"
      }
    }
    return Accounts.createUser(newUser);
  }
});
```

and this is the error

```
Error: Match error: Expected function, got undefined in field validate
    at exports.check (packages/check.js:57:15)
    at new ValidatedMethod (packages/mdg:validated-method/validated-method.js:23:5)
    at meteorInstall.imports.api.users.methods.js (imports/api/users/methods.js:7:14)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/neutron92/.meteor/packages/modules/.0.7.7.142c1d6++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.imports.startup.server.api.js (imports/startup/server/api.js:1:8)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/neutron92/.meteor/packages/modules/.0.7.7.142c1d6++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

Please help me

**Comment by hich-em** [comment]
resolved

meteor add aldeed:simple-schema@1.5.3
